language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install slackclient==1.0.7
  - pip install nose pylint
# command to run tests
script: find . -name "*.py" | xargs pylint -E
